### ISSUE TITLE
Upserting an advert - PUT /api/v2/client/adverts/upsert?code=ABC123

### ISSUE THREAD

**Issue by nhakhtn** [exchangegroup/api.marketplacer.com#13]
3 days ago it worked, now it doesn't
i got this message:
string(185) "{"errors":[{"title":"Record not found","detail":"The record identified by upsert could not be found.","id":null,"href":null,"code":404,"source":null,"links":null,"status":"not_found"}]}"

**Comment by mipearson** [comment]
Apologies for not keeping you in the loop on this, but we needed to remove `upsert` endpoint due to schema incompatibilities.

We've also added an `external_id` field to be used instead of `code`.

You will need to handle `upsert` behaviour in your integration by searching for a matching advert:

`api/v2/client/adverts/?external_id=MYEXTERNALID`

and then either create a new advert or update the one that was returned from the search.

**Comment by nhakhtn** [comment]
thanks for information!
